Add works section
TahenyBELGUITH/Portfolio-mobile-version pull request #2
Opened 2021-07-14 14:10 UTC by TahenyBELGUITH

in this part:
I use Grid display
Flex Display

2021-07-14 17:56 UTC, tahiry-dev requested changes
Hello @TahenyBELGUITH 👋
You did a great job creating this mobile version of your portfolio,  but you need to update some markup and page design before moving to the next step!

## Required Changes ♻️
Please follow the design correctly, mostly in terms of alignements.
Here are examples of your pages:
![seeProject](https://user-images.githubusercontent.com/47100064/125669279-b19afff8-efb2-4dda-b4ea-0223ab9d7fd6.png)
![getResume](https://user-images.githubusercontent.com/47100064/125669311-ee7f629f-3556-4367-b223-26294f102dc7.png)
As you can see, the call to action is not aligned properly.
For a quick reminder, please look at the design
![correct](https://user-images.githubusercontent.com/47100064/125669426-f8503bd7-249c-4e08-bb36-c093f9fb86f0.png)
- Semantic HTML are powerful tools to organize your code clearly, _Kindly check the comments under the review._

## Optional suggestions
_Although the following suggestions are optional, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-14 17:56 UTC, tahiry-dev commented on index.html
> +    </section>
-I suggest you to create a main container that wraps all of your projects section and where you can add display: grid. And Controller individual project alignment with flexbox

2021-07-14 17:56 UTC, tahiry-dev commented on index.html
> +        <p><a href="#">LET'S CONNECT</a></p>
'Let's connect' is another important sentence on your about me page so please use  header tag

2021-07-14 17:56 UTC, tahiry-dev commented on index.html
> +                            <span class="html"><img src="./images/html.svg" alt="html">html</span>
You implemented nice images here, but it is better if you use it as a background image, please

2021-07-14 17:56 UTC, tahiry-dev commented on index.html
> +        <button class="tonic-button-submit about-btn" type="submit">Get my resume </button>
Please style your call to action button for Active, Hover, and Pressed. Please refer to the design for that

2021-07-15 06:39 UTC, TahenyBELGUITH commented on index.html
> +    </section>
done

2021-07-15 06:39 UTC, TahenyBELGUITH commented on index.html
> +        <p><a href="#">LET'S CONNECT</a></p>
done

2021-07-15 06:39 UTC, TahenyBELGUITH commented on index.html
> +                            <span class="html"><img src="./images/html.svg" alt="html">html</span>
done

2021-07-15 06:40 UTC, TahenyBELGUITH commented on index.html
> +        <button class="tonic-button-submit about-btn" type="submit">Get my resume </button>
done

2021-07-17 09:18 UTC, Emmyn5600 approved these changes
## Status: Approved :heavy_check_mark: :muscle::clap:

Hi @TahenyBELGUITH 

Your project is complete! Great job for making the necessary changes recommended by the previous reviewer. There is nothing else to say other than... it's time to merge it :+1:.
Congratulations! :tada:

### Optional suggestions
* The button (e.g., "See project") is a link a or button tag, great work you did it however,  follow the button styling: Active, Hover and Pressed (see design).
* Try to reduce the image width for the work section to meet the mobile version from Figma.


Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-07-17 09:19 UTC, merged