Desktop version
TahenyBELGUITH/Portfolio-mobile-version pull request #7
Opened 2021-07-27 07:20 UTC by TahenyBELGUITH

I resize the size 
I check all the images alternatives 
I check the text headings

2021-07-27 09:20 UTC, rloterh requested changes
Hi Tahtouha, 

You did extremely great on this project!👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there!👍 

## Good Points 👍  
- No linter errors

## Required Changes ♻️
- [ ] _Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-27 09:20 UTC, rloterh commented on README.md
> +- I add accessibily
- [ ] There are a number of accessibility points which were not highlighted in your report: Kindly ensure to make assessment on the following points and include reports on them accordingly as well:
- Page titles
- Image text alternatives `** (<img alt="alt text">)`
- Text headings
- Color contrast
- Resize
- Interaction
- Moving content
- Multimedia
- The basic structure of the page

2021-07-28 13:25 UTC, hemant-soni-vst-au4 requested changes
Hi @TahenyBELGUITH , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Alt Text](https://media.giphy.com/media/q6U4fbreC4Neo/giphy.gif)
 ## Required Changes ♻️
_Check the comments under the review._

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-28 13:25 UTC, hemant-soni-vst-au4 commented on index.html
>              <a href="./index.html"><img class="toolbar-img2" src="images/logo.svg" alt="Logo"></a>
- [ ] As highlighted by a previous reviewer the sub-contents of the navbar are well spaced from the original design. Right now there is a need for a little more margin or padding. Kindly fix this issue.

yours
![image](https://user-images.githubusercontent.com/53019916/127328888-caee9c4c-51a5-4e3c-912a-ec0107ef9aea.png)

Original 
![image](https://user-images.githubusercontent.com/53019916/127329008-de94753c-494b-45fa-a651-e8f85df22e5e.png)

2021-07-28 13:25 UTC, hemant-soni-vst-au4 commented on README.md
> +  - The basic structure of the page
- [ ] As per project requirements and issues highlighted by the previous reviewer, We have to prepare a report listing all points that you have checked, and the result of your evaluation. Add our report to the description of your pull request.

![image](https://user-images.githubusercontent.com/53019916/127329624-1afd69b8-c079-4699-b256-1c03ad4f6bad.png)

2021-07-28 16:42 UTC, Shaher-11 approved these changes
#### Hello @TahenyBELGUITH,

# Congratulations! 🎉 
#### Your project is approved!  There is nothing else to say other than... it's time to merge it :muscle: :muscle::muscle:

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

2021-07-28 20:16 UTC, merged