Manipulate  the humberger button with javascript
TahenyBELGUITH/Portfolio-mobile-version pull request #8
Opened 2021-08-03 08:27 UTC by TahenyBELGUITH

In this branch:
 I add script file
I manipulate the hamburger button using javascript

2021-08-04 20:05 UTC, Davidosky007 requested changes
# Hi @TahenyBELGUITH 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
* Always try to make your commit message descriptive I can see your commit messages are not descriptive kindly fix it 🙏
* Kindly ensure you stick to the design as much as possible  
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-05 15:04 UTC, dasileker requested changes
### **Hi @TahenyBELGUITH** 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-05 15:04 UTC, dasileker commented on index.html
> +                &#9776;
- [ ] hello this function for your menu should contain also an `X` icon and target it to close [see here the specs](https://user-images.githubusercontent.com/61562626/128371981-d4de0a01-3cfb-42f0-b768-4480d05f88bb.jpeg)
-  it should contain an `X` after opening the menu [original](https://user-images.githubusercontent.com/61562626/128372965-ca9062c6-8377-41b5-997e-004e60f410a1.png) , and your is
![btn1](https://user-images.githubusercontent.com/61562626/128373054-cc6bc217-40cd-4d75-b216-a35eceaeb28d.gif)

2021-08-06 00:42 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @TahenyBELGUITH 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you, please fix the "optional" feature before your next milestone, I'm approving this milestone in order for you to not repeat a week, keep the good work👍🏽 

![believe in change](https://user-images.githubusercontent.com/60631456/128438809-e0e713fe-dbfe-441e-bc32-31d3d8756aaf.gif)

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-06 00:42 UTC, mricanho commented on index.html
> +                </div>
- [ ] [OPTIONAL] I'm gonna put this as optional, but it's really mandatory, when you open your website on a mobile device, the menu it's open by default, please change it to display: none by default, other than that your mobile menu works well.

[Check this link and open it on a mobile device](https://rawcdn.githack.com/TahenyBELGUITH/Portfolio-mobile-version/efba87ce29831814eb9862a814da4ac199bb07cc/index.html)

2021-08-06 06:29 UTC, merged